# Generated by Django 5.2.1 on 2025-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='duration',
            field=models.IntegerField(editable=False, help_text='Duration in days'),
        ),
    ]
