# Generated by Django 5.2 on 2025-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
