# Generated by Django 5.2.1 on 2025-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(help_text='4 digits on the back of your card', max_length=4),
        ),
    ]
